name: Chris Hatton
favicon: null
layout_spectrum: 0.12280162749812007
typography_spectrum: 0.8969829154666513
title: ckhatton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41558162262663245
  lightness: 0.01771945832297206
  saturation: 0.8303793868981302
  rhythmicContrast: 0.32016892242245376
purpose: []
