name: Chris Hatton
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64624
title: ckhatton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8fc1d8'
    - '#000000'
    - '#d88021'
    - '#ffffff'
    - '#6d3d09'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
